# Generated by Django 5.2 on 2025-11-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='deeplink',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='qr_string',
            field=models.TextField(blank=True),
        ),
    ]
